function logmsg(stack, fmt, varargin)

indent = repmat(' ',1,length(stack)-1);

if ~isempty(stack)
    str = sprintf('%s (line %d): ', stack(1).file, stack(1).line);
    link = sprintf(...
            '%s%s (<a href="matlab: matlab.desktop.editor.openAndGoToLine(''%s'', %d);">line %d</a>)',...
            indent,...
            stack(1).file,...
            which(stack(1).file),...
            stack(1).line,...
            stack(1).line);
    fmtx = fmt(end);
    fmt = strrep(fmt(1:end-1), '\n', ['\n',repmat(' ', 1, length(str))]);
    fprintf([link, ': ', fmt, fmtx], varargin{:});
else
    fprintf(fmt, varargin{:});
end
