function logmsg(stack, fmt, varargin)

if ~isempty(stack)
    link = sprintf(...
            '%s (<a href="matlab: opentoline(''%s''), %d)">line %d</a>)',...
            stack(1).file,...
            stack(1).file,...
            stack(1).line,...
            stack(1).line);
    fprintf([link, ': ', fmt], varargin{:});
else
    fprintf(fmt, varargin{:});
end
